import './globals.css';

import { M_PLUS_Rounded_1c, Rowdies } from '@next/font/google';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const titleFont = Rowdies({ subsets: ['latin'], weight: '400' });
const baseFont = M_PLUS_Rounded_1c({ subsets: ['latin'], weight: '400' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="h-full w-full">
      <head>
        <title>BINGOBANG ONLINE</title>
      </head>
      <body
        className={`${baseFont.className} h-full w-full flex flex-col text-primary-normal`}
      >
        <header className="flex justify-center py-12 px-4 grow-0 bg-primary-lighter text-white">
          <h1 className={`text-5xl ${titleFont.className}`}>
            <Link href="/">BINGOBANG ONLINE</Link>
          </h1>
        </header>
        <div className="py-8 grow">{children}</div>
        <footer className="bg-primary-lighter grow-0 py-2 font-black text-center text-primary-darken">
          &copy; 2023 Masaharu nemoto
        </footer>
      </body>
    </html>
  );
}
